import { describe } from "jsr:@std/testing/bdd";
import { Sol1_1255, Sol2_1255 } from "./1255-maximum-score-words-formed-by-letters.ts";

describe("bench", () => {
  const [a, b, c] = [
    [
      "bhtgqlbhbko",
      "emnnd",
      "seilhhmjatngm",
      "tjjpempmhioeakm",
      "tpmicqabgpbdmkl",
      "pbfpg",
      "ajjpeojacckgl",
      "pcssptkteqi",
      "mieolfbmjkb",
      "eqshjsiq",
      "kqnfgl",
      "sqmcmsm",
      "ttktnasfktfdr",
      "ddmpgoq",
    ],
    [
      "a",
      "b",
      "b",
      "b",
      "b",
      "c",
      "c",
      "c",
      "d",
      "d",
      "d",
      "d",
      "d",
      "e",
      "e",
      "e",
      "e",
      "e",
      "e",
      "f",
      "f",
      "f",
      "f",
      "f",
      "g",
      "g",
      "g",
      "g",
      "g",
      "h",
      "h",
      "h",
      "h",
      "i",
      "i",
      "i",
      "j",
      "j",
      "j",
      "j",
      "k",
      "k",
      "l",
      "l",
      "l",
      "l",
      "l",
      "l",
      "l",
      "m",
      "m",
      "n",
      "n",
      "n",
      "o",
      "p",
      "p",
      "p",
      "p",
      "p",
      "p",
      "q",
      "q",
      "q",
      "q",
      "q",
      "q",
      "r",
      "s",
      "s",
      "s",
      "t",
      "t",
      "t",
      "t",
      "t",
    ],
    [2, 6, 3, 7, 5, 9, 4, 4, 8, 1, 6, 9, 1, 1, 1, 1, 7, 5, 2, 5, 0, 0, 0, 0, 0, 0],
  ];

  Deno.bench("sol1 - maxScoreWords", () => {
    Sol1_1255.maxScoreWords(a, b, c);
  });

  Deno.bench("sol2 - maxScoreWords", () => {
    Sol2_1255.maxScoreWords(a, b, c);
  });
});
