import { exercise } from "@shared/utilities/exercise.ts";
import { bench, describe } from "vitest";
import { Sol1_1255 } from "./1255-maximum-score-words-formed-by-letters.ts";

exercise(Sol1_1255.maxScoreWords, [
  [
    [
      [
        "bhtgqlbhbko",
        "emnnd",
        "seilhhmjatngm",
        "tjjpempmhioeakm",
        "tpmicqabgpbdmkl",
        "pbfpg",
        "ajjpeojacckgl",
        "pcssptkteqi",
        "mieolfbmjkb",
        "eqshjsiq",
        "kqnfgl",
        "sqmcmsm",
        "ttktnasfktfdr",
        "ddmpgoq",
      ],
      [
        "a",
        "b",
        "b",
        "b",
        "b",
        "c",
        "c",
        "c",
        "d",
        "d",
        "d",
        "d",
        "d",
        "e",
        "e",
        "e",
        "e",
        "e",
        "e",
        "f",
        "f",
        "f",
        "f",
        "f",
        "g",
        "g",
        "g",
        "g",
        "g",
        "h",
        "h",
        "h",
        "h",
        "i",
        "i",
        "i",
        "j",
        "j",
        "j",
        "j",
        "k",
        "k",
        "l",
        "l",
        "l",
        "l",
        "l",
        "l",
        "l",
        "m",
        "m",
        "n",
        "n",
        "n",
        "o",
        "p",
        "p",
        "p",
        "p",
        "p",
        "p",
        "q",
        "q",
        "q",
        "q",
        "q",
        "q",
        "r",
        "s",
        "s",
        "s",
        "t",
        "t",
        "t",
        "t",
        "t",
      ],
      [2, 6, 3, 7, 5, 9, 4, 4, 8, 1, 6, 9, 1, 1, 1, 1, 7, 5, 2, 5, 0, 0, 0, 0, 0, 0],
    ],
    171,
  ],
  [
    [
      ["dog", "cat", "dad", "good"],
      ["a", "a", "c", "d", "d", "d", "g", "o", "o"],
      [1, 0, 9, 5, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    ],
    23,
  ],
  [
    [
      ["xxxz", "ax", "bx", "cx"],
      ["z", "a", "b", "c", "x", "x", "x"],
      [4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 10],
    ],
    27,
  ],
  [
    [
      ["leetcode"],
      ["l", "e", "t", "c", "o", "d"],
      [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    ],
    0,
  ],
  [
    [
      ["add", "dda", "bb", "ba", "add"],
      ["a", "a", "a", "a", "b", "b", "b", "b", "c", "c", "c", "c", "c", "d", "d", "d"],
      [3, 9, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    ],
    51,
  ],
]);
